/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author rodri
 */
public class Menu_GUI extends javax.swing.JFrame {

    
    public Menu_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dados = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        cod1_txt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nome1_txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        end1_txt = new javax.swing.JTextField();
        consultar_BTN = new javax.swing.JButton();
        alterar_BTN = new javax.swing.JButton();
        LIMPAR_BTN = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        cod2_txt = new javax.swing.JTextField();
        EXCLUIR_BTN = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        placa_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        marca_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        modelo_txt = new javax.swing.JTextField();
        FECHAR_BTN = new javax.swing.JButton();
        SALVAR_BTN = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        horarioe_txt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(null);

        dados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(dados);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 400, 90);

        jLabel5.setText("CÓDIGO : ");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 100, 80, 30);
        jPanel2.add(cod1_txt);
        cod1_txt.setBounds(80, 100, 90, 30);

        jLabel6.setText("MARCA: ");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 150, 70, 20);
        jPanel2.add(nome1_txt);
        nome1_txt.setBounds(80, 140, 190, 30);

        jLabel7.setText("MODELO:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 190, 90, 14);
        jPanel2.add(end1_txt);
        end1_txt.setBounds(80, 180, 190, 30);

        consultar_BTN.setText("CONSULTAR");
        consultar_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar_BTNActionPerformed(evt);
            }
        });
        jPanel2.add(consultar_BTN);
        consultar_BTN.setBounds(280, 100, 110, 30);

        alterar_BTN.setText("ALTERAR");
        alterar_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterar_BTNActionPerformed(evt);
            }
        });
        jPanel2.add(alterar_BTN);
        alterar_BTN.setBounds(280, 140, 110, 30);

        LIMPAR_BTN.setText("LIMPAR");
        LIMPAR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LIMPAR_BTNActionPerformed(evt);
            }
        });
        jPanel2.add(LIMPAR_BTN);
        LIMPAR_BTN.setBounds(280, 180, 110, 30);

        jLabel8.setText("PLACA:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 220, 60, 30);
        jPanel2.add(jTextField1);
        jTextField1.setBounds(80, 220, 190, 30);

        jTabbedPane1.addTab("CONSULTAR/ ALTERAR", jPanel2);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 255));
        jLabel9.setText("INFORME O CÓDIGO A SER EXCLUIDO");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(50, 20, 320, 70);

        cod2_txt.setToolTipText("INSIRA O CÓDIGO A SER EXCLUIDO !");
        jPanel3.add(cod2_txt);
        cod2_txt.setBounds(140, 100, 120, 20);

        EXCLUIR_BTN.setText("EXCLUIR ");
        EXCLUIR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXCLUIR_BTNActionPerformed(evt);
            }
        });
        jPanel3.add(EXCLUIR_BTN);
        EXCLUIR_BTN.setBounds(150, 160, 100, 30);

        jTabbedPane1.addTab("EXCLUIR", jPanel3);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("CADASTRAR CARRO");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 10, 210, 40);

        jLabel2.setText("PLACA:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 50, 70, 30);
        jPanel1.add(placa_txt);
        placa_txt.setBounds(100, 50, 230, 30);

        jLabel3.setText("MARCA:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 90, 120, 30);
        jPanel1.add(marca_txt);
        marca_txt.setBounds(100, 90, 230, 30);

        jLabel4.setText("MODELO:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 140, 80, 20);
        jPanel1.add(modelo_txt);
        modelo_txt.setBounds(100, 130, 230, 30);

        FECHAR_BTN.setText("FECHAR");
        FECHAR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FECHAR_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(FECHAR_BTN);
        FECHAR_BTN.setBounds(300, 230, 80, 30);

        SALVAR_BTN.setText("SALVAR");
        SALVAR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALVAR_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(SALVAR_BTN);
        SALVAR_BTN.setBounds(30, 230, 100, 30);

        jLabel11.setText("Horário de entrada:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(0, 170, 100, 30);

        horarioe_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horarioe_txtActionPerformed(evt);
            }
        });
        jPanel1.add(horarioe_txt);
        horarioe_txt.setBounds(100, 170, 230, 30);

        jButton1.setText("?");
        jPanel1.add(jButton1);
        jButton1.setBounds(330, 170, 40, 30);

        jTabbedPane1.addTab("CADASTRAR", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(400, 306));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void consultar_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar_BTNActionPerformed
        //Model.CRUD_DAO.consultar();

    }//GEN-LAST:event_consultar_BTNActionPerformed

    private void alterar_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterar_BTNActionPerformed
        //Model.CRUD_DAO.atualizar();
    }//GEN-LAST:event_alterar_BTNActionPerformed

    private void LIMPAR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LIMPAR_BTNActionPerformed
        //Model.CRUD_DAO.limpar();
    }//GEN-LAST:event_LIMPAR_BTNActionPerformed

    private void EXCLUIR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXCLUIR_BTNActionPerformed
        //String x = JOptionPane.showInputDialog(null,"Deseja realmente excluir o registro?\n1-Sim\n2-Não");
        //int op = Integer.parseInt(x);
        //if(op == 1 ){
          //  Model.CRUD_DAO.excluir();
         //   JOptionPane.showMessageDialog(null,"Registro excluido com sucesso !");
        //    cod2_txt.setText("");
       //     refresh();
      //  }else{
       //     JOptionPane.showMessageDialog(null,"Registro não excluido");
       // }
    }//GEN-LAST:event_EXCLUIR_BTNActionPerformed

    private void FECHAR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FECHAR_BTNActionPerformed
        System.exit(0);
    }//GEN-LAST:event_FECHAR_BTNActionPerformed

    private void SALVAR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALVAR_BTNActionPerformed
        Model.Menu_DAO.salvar();
    }//GEN-LAST:event_SALVAR_BTNActionPerformed

    private void horarioe_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horarioe_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horarioe_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EXCLUIR_BTN;
    private javax.swing.JButton FECHAR_BTN;
    private javax.swing.JButton LIMPAR_BTN;
    private javax.swing.JButton SALVAR_BTN;
    private javax.swing.JButton alterar_BTN;
    public static javax.swing.JTextField cod1_txt;
    public static javax.swing.JTextField cod2_txt;
    private javax.swing.JButton consultar_BTN;
    public static javax.swing.JTable dados;
    public static javax.swing.JTextField end1_txt;
    public static javax.swing.JTextField horarioe_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JTextField jTextField1;
    public static javax.swing.JTextField marca_txt;
    public static javax.swing.JTextField modelo_txt;
    public static javax.swing.JTextField nome1_txt;
    public static javax.swing.JTextField placa_txt;
    // End of variables declaration//GEN-END:variables
}
