/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author rodri
 */
public class Menu_GUI extends javax.swing.JFrame {

    
    public Menu_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("script?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        carroQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM Carro c");
        carroList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : carroQuery.getResultList();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        consultarMarca_txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        consultarModelo_txt = new javax.swing.JTextField();
        consultar_BTN = new javax.swing.JButton();
        alterar_BTN = new javax.swing.JButton();
        LIMPAR_BTN = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        consultarPlaca_txt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        consultarHorarioEntrada_txt = new javax.swing.JTextField();
        interrogacon_btn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        excluirPlaca_txt = new javax.swing.JTextField();
        EXCLUIR_BTN = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        horarios_txt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        interrogabol_btn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        placa_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        marca_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        modelo_txt = new javax.swing.JTextField();
        FECHAR_BTN = new javax.swing.JButton();
        SALVAR_BTN = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        horarioe_txt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(null);

        jLabel6.setText("MARCA: ");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 140, 70, 30);
        jPanel2.add(consultarMarca_txt);
        consultarMarca_txt.setBounds(70, 140, 190, 30);

        jLabel7.setText("MODELO:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 180, 90, 30);
        jPanel2.add(consultarModelo_txt);
        consultarModelo_txt.setBounds(70, 180, 190, 30);

        consultar_BTN.setText("CONSULTAR");
        consultar_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar_BTNActionPerformed(evt);
            }
        });
        jPanel2.add(consultar_BTN);
        consultar_BTN.setBounds(280, 100, 110, 30);

        alterar_BTN.setText("ALTERAR");
        alterar_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterar_BTNActionPerformed(evt);
            }
        });
        jPanel2.add(alterar_BTN);
        alterar_BTN.setBounds(280, 140, 110, 30);

        LIMPAR_BTN.setText("LIMPAR");
        LIMPAR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LIMPAR_BTNActionPerformed(evt);
            }
        });
        jPanel2.add(LIMPAR_BTN);
        LIMPAR_BTN.setBounds(280, 180, 110, 30);

        jLabel8.setText("PLACA:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 100, 60, 30);
        jPanel2.add(consultarPlaca_txt);
        consultarPlaca_txt.setBounds(70, 100, 190, 30);

        jLabel10.setText("HORÁRIO DE ENTRADA:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(0, 220, 120, 50);
        jPanel2.add(consultarHorarioEntrada_txt);
        consultarHorarioEntrada_txt.setBounds(120, 230, 210, 30);

        interrogacon_btn.setText("?");
        interrogacon_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interrogacon_btnActionPerformed(evt);
            }
        });
        jPanel2.add(interrogacon_btn);
        interrogacon_btn.setBounds(330, 230, 60, 30);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, carroList, tabela);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${placa}"));
        columnBinding.setColumnName("Placa");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${marca}"));
        columnBinding.setColumnName("Marca");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${modelo}"));
        columnBinding.setColumnName("Modelo");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${horarioEntrada}"));
        columnBinding.setColumnName("Horario de Entrada");
        columnBinding.setColumnClass(java.util.Date.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane3.setViewportView(tabela);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(0, 0, 400, 90);

        jTabbedPane1.addTab("CONSULTAR/ ALTERAR", jPanel2);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 255));
        jLabel9.setText("INFORME A PLACA DO CARRO PARA GERAR O BOLETO");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(30, 0, 330, 60);

        excluirPlaca_txt.setToolTipText("INSIRA O CÓDIGO A SER EXCLUIDO !");
        jPanel3.add(excluirPlaca_txt);
        excluirPlaca_txt.setBounds(140, 70, 120, 30);

        EXCLUIR_BTN.setText("EXCLUIR ");
        EXCLUIR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXCLUIR_BTNActionPerformed(evt);
            }
        });
        jPanel3.add(EXCLUIR_BTN);
        EXCLUIR_BTN.setBounds(150, 180, 100, 30);

        jLabel5.setText("PLACA:");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(60, 70, 70, 30);
        jPanel3.add(horarios_txt);
        horarios_txt.setBounds(140, 130, 120, 30);

        jLabel12.setText("HORÁRIO DE SAÍDA:");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(10, 130, 130, 30);

        interrogabol_btn.setText("?");
        interrogabol_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interrogabol_btnActionPerformed(evt);
            }
        });
        jPanel3.add(interrogabol_btn);
        interrogabol_btn.setBounds(260, 130, 50, 30);

        jTabbedPane1.addTab("EXCLUIR/BOLETO", jPanel3);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("CADASTRAR CARRO");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 10, 210, 40);

        jLabel2.setText("PLACA:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 50, 70, 30);
        jPanel1.add(placa_txt);
        placa_txt.setBounds(100, 50, 230, 30);

        jLabel3.setText("MARCA:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 90, 120, 30);
        jPanel1.add(marca_txt);
        marca_txt.setBounds(100, 90, 230, 30);

        jLabel4.setText("MODELO:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 140, 80, 20);
        jPanel1.add(modelo_txt);
        modelo_txt.setBounds(100, 130, 230, 30);

        FECHAR_BTN.setText("FECHAR");
        FECHAR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FECHAR_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(FECHAR_BTN);
        FECHAR_BTN.setBounds(300, 230, 80, 30);

        SALVAR_BTN.setText("SALVAR");
        SALVAR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALVAR_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(SALVAR_BTN);
        SALVAR_BTN.setBounds(30, 230, 100, 30);

        jLabel11.setText("Horário de entrada:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(0, 170, 100, 30);

        horarioe_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horarioe_txtActionPerformed(evt);
            }
        });
        jPanel1.add(horarioe_txt);
        horarioe_txt.setBounds(100, 170, 230, 30);

        jButton1.setText("?");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(330, 170, 40, 30);

        jTabbedPane1.addTab("CADASTRAR", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        setSize(new java.awt.Dimension(405, 306));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void consultar_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar_BTNActionPerformed
        Model.Menu_DAO.consultar();

    }//GEN-LAST:event_consultar_BTNActionPerformed

    private void alterar_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterar_BTNActionPerformed
        Model.Menu_DAO.alterar();
    }//GEN-LAST:event_alterar_BTNActionPerformed

    private void LIMPAR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LIMPAR_BTNActionPerformed
        //Model.CRUD_DAO.limpar();
    }//GEN-LAST:event_LIMPAR_BTNActionPerformed

    private void EXCLUIR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXCLUIR_BTNActionPerformed
        Model.Menu_DAO.excluir();
    }//GEN-LAST:event_EXCLUIR_BTNActionPerformed

    private void FECHAR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FECHAR_BTNActionPerformed
        System.exit(0);
    }//GEN-LAST:event_FECHAR_BTNActionPerformed

    private void SALVAR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALVAR_BTNActionPerformed
        Model.Menu_DAO.salvar();
    }//GEN-LAST:event_SALVAR_BTNActionPerformed

    private void horarioe_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horarioe_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horarioe_txtActionPerformed

    private void interrogabol_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interrogabol_btnActionPerformed
        Model.Menu_DAO.interroga();
    }//GEN-LAST:event_interrogabol_btnActionPerformed

    private void interrogacon_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interrogacon_btnActionPerformed
       Model.Menu_DAO.interroga();
    }//GEN-LAST:event_interrogacon_btnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Model.Menu_DAO.interroga();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EXCLUIR_BTN;
    private javax.swing.JButton FECHAR_BTN;
    private javax.swing.JButton LIMPAR_BTN;
    private javax.swing.JButton SALVAR_BTN;
    private javax.swing.JButton alterar_BTN;
    private java.util.List<View.Carro> carroList;
    private javax.persistence.Query carroQuery;
    public static javax.swing.JTextField consultarHorarioEntrada_txt;
    public static javax.swing.JTextField consultarMarca_txt;
    public static javax.swing.JTextField consultarModelo_txt;
    public static javax.swing.JTextField consultarPlaca_txt;
    private javax.swing.JButton consultar_BTN;
    private javax.persistence.EntityManager entityManager;
    public static javax.swing.JTextField excluirPlaca_txt;
    public static javax.swing.JTextField horarioe_txt;
    public static javax.swing.JTextField horarios_txt;
    public static javax.swing.JButton interrogabol_btn;
    public static javax.swing.JButton interrogacon_btn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    public static javax.swing.JTextField marca_txt;
    public static javax.swing.JTextField modelo_txt;
    public static javax.swing.JTextField placa_txt;
    public static javax.swing.JTable tabela;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
